name: sprawozdanie_pdf
on: push
jobs:
  sprawozdanie:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-get install texlive-xetex inkspace pandoc
      - uses: actions/checkout@v4
      - run: pip install pint open-atmos-jupyter-utilis scipy nbconvert ipykernel
      - run: python -m nbconvert --to script --execute lab1.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: sprawozdanie.pdf